"""Add purchase_price and selling_price to payments

Revision ID: 57ada1c17ff5
Revises: a09e2f8f60cd
Create Date: 2025-12-15 00:10:31.919577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57ada1c17ff5'
down_revision = 'a09e2f8f60cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paypal_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paypal_webhook_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_paypal_webhook_events_event_type'))

    op.drop_table('paypal_webhook_events')
    with op.batch_alter_table('payments_admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_admin_users_username'))

    op.drop_table('payments_admin_users')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('selling_price')
        batch_op.drop_column('purchase_price')

    op.create_table('payments_admin_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_admin_users_pkey'))
    )
    with op.batch_alter_table('payments_admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_admin_users_username'), ['username'], unique=True)

    op.create_table('paypal_webhook_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('raw_event', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('paypal_webhook_events_pkey'))
    )
    with op.batch_alter_table('paypal_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paypal_webhook_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_paypal_webhook_events_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###
